### ISSUE TITLE
Add spans for status badges

### ISSUE THREAD

**Issue by roman-yagodin** [volgau/redmine_volgau#2]
This would allow to apply custom CSS (like coloring) to issue statuses.

**Comment by roman-yagodin** [comment]
Sample styles:

```CSS
.status-badge {
  display: inline-block;
  float: left;
  width: 16px;
  height: 16px;
  margin-right: 0.5rem;
  border: 1px solid gray;
}

.status-badge-status-2 {
  background-color: green;
}
```
